language:
  - java
  - node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
jdk:
  - openjdk11
before_install:
  - chmod +x build.sh
script:
  - ./build-react.sh
  - ./build-spring.sh