language:
  - java
  - node_js
node_js:
  - 10.23.0
cache:
  directories:
    - node_modules
jdk:
  - openjdk11
before_install:
  - chmod +x build-react.sh
  - chmod +x build-spring.sh
script:
  - ./build-react.sh
  - ./build-spring.sh