jobs:
  include:
    - stage: "Build"
      name: "Build"
      language: node_js
      node_js: 14.15.4
      cache:
        directories:
          - node_modules
      before_install:
        - chmod +x build-react.sh
      script:
        - ./build-react.sh

    - stage: "Deploy"
      name: "Deploy"
      language: java
      jdk: openjdk11
      before_install:
        - cd Backend/store
        - chmod +x deploy-spring.sh
      script:
        - ./deploy-spring.sh
