jobs:
  include:
    -stage: java build
      - language: java
        jdk: openjdk11
        before_install:
          - cd Backend/store
          - chmod +x build-spring.sh
        script:
          - ./build-spring.sh