jobs:
  include:
    - language: java
      jdk: openjdk11
      before_install:
        - cd Backend/store
        - chmod +x build-spring.sh
      script:
        - ./build-spring.sh

    # - language: node_js
    #   node_js: 14.15.4
    #   cache:
    #     directories:
    #       - node_modules
    #   before_install:
    #     - chmod +x build-react.sh
    #   script:
    #     - ./build-react.sh